export type PropertyDto = {
  id: string;
  sourceProvider: string;
  sourceUrl: string | null;
  sourceListingId: string | null;
  sourceListingKey: string | null;
  sourceObservedAt: string;
  sourceMetadata: unknown;
  title: string;
  description: string | null;
  propertyType: 'APARTMENT' | 'HOUSE' | 'LAND' | 'OTHER';
  operationType: 'SALE';
  priceAmount: number | null;
  priceCurrency: string | null;
  street: string | null;
  exteriorNumber: string | null;
  interiorNumber: string | null;
  neighborhood: string | null;
  municipality: string | null;
  state: string | null;
  postalCode: string | null;
  countryCode: string;
  formattedAddress: string | null;
  latitude: number | null;
  longitude: number | null;
  landAreaM2: number | null;
  constructionAreaM2: number | null;
  bedrooms: number | null;
  bathrooms: number | null;
  parkingSpaces: number | null;
  parkingType: string | null;
  serviceRoom: boolean | null;
  propertyAgeYears: number | null;
  condition: string | null;
  orientation: string | null;
  landUse: string | null;
  buildingLevels: number | null;
  unitFloor: number | null;
  maintenanceAmount: number | null;
  maintenanceCurrency: string | null;
  technicalSheetQrUrl: string | null;
  agentName: string | null;
  agentAvatarUrl: string | null;
  agentPhones: string[];
  agentEmail: string | null;
  officeName: string | null;
  sourceOfficeId: string | null;
  decisionStatus: 'NEW' | 'CONTACTED' | 'VISIT_SCHEDULED' | 'VISITED' | 'OFFER_MADE' | 'REJECTED' | 'PURCHASED';
  isFavorite: boolean;
  rating: number | null;
  notes: string | null;
  visitAt: string | null;
  rejectionReason: string | null;
  archivedAt: string | null;
  publicationStatus: 'DRAFT' | 'PUBLISHED';
  createdAt: string;
  updatedAt: string;
  images: { id: string; propertyId: string; url: string; alt: string | null; sortOrder: number }[];
  features: { id: string; propertyId: string; category: 'AREA' | 'EQUIPMENT' | 'OTHER'; name: string }[];
};
export type ImportStatus = 'QUEUED' | 'FETCHING' | 'RENDERING' | 'EXTRACTING' | 'READY' | 'FAILED';
export type ImportKind = 'STANDARD' | 'ENHANCEMENT';
export type ImportJobDto = {
  id: string;
  kind: ImportKind;
  status: ImportStatus;
  propertyId: string | null;
  errorMessage: string | null;
  retryCount: number;
};
export type ImportStartDto =
  | { existing: true; propertyId: string; publicationStatus: 'DRAFT' | 'PUBLISHED' }
  | { importId: string; status: ImportStatus };

export type EnhancementCapabilityDto = { available: boolean; reason: string | null };
export type EnhancementChangeDto = { field: string; label: string; current: string | null; proposed: string };
export type EnhancementPreviewDto = {
  importId: string;
  propertyId: string;
  changes: EnhancementChangeDto[];
  addedImages: string[];
  addedFeatures: { category: 'AREA' | 'EQUIPMENT' | 'OTHER'; name: string }[];
};
